version: "2"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
    container_name: elasticsearch-hands-on-2
    environment:
     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
     - "discovery.type=single-node"
     - xpack.monitoring.collection.enabled=true
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch-hands-on-2-data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:7.8.0
    environment:
      - "ELASTICSEARCH_HOSTS=http://elasticsearch-hands-on-2:9200"
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

volumes:
  elasticsearch-hands-on-2-data:
    external: true

