version: "2"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.0
    container_name: elasticsearch-hands-on-2
    environment:
     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
     - "xpack.security.enabled=false"
     - "discovery.type=single-node"
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch-hands-on-2-data:/usr/share/elasticsearch/data
    networks:
      - esnet

  kibana:
    image: docker.elastic.co/kibana/kibana:6.6.0
    environment:
      - "ELASTICSEARCH_URL=http://elasticsearch-hands-on-2:9200"
    ports:
      - "5601:5601"
    networks:
      - esnet
    depends_on:
      - elasticsearch

volumes:
  elasticsearch-hands-on-2-data:
    external: true

networks:
  esnet:
    driver: bridge
