version: "2"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.0
    container_name: elasticsearch1
    environment:
     - cluster.name=docker-cluster
     - bootstrap.memory_lock=true
     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
     - xpack.security.enabled=false
     - xpack.monitoring.collection.enabled=true
     - xpack.monitoring.exporters.remote.type=http
     - xpack.monitoring.exporters.remote.host=http://monitor:9200
     - discovery.zen.minimum_master_nodes=2
     - discovery.zen.ping.unicast.hosts=elasticsearch1,elasticsearch2,elasticsearch3
     - discovery.zen.fd.ping_timeout=5s
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 1g
    cap_add:
      - IPC_LOCK
    ports:
      - "19200:9200"
    networks:
      - esnet

  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.0
    container_name: elasticsearch2
    environment:
     - cluster.name=docker-cluster
     - bootstrap.memory_lock=true
     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
     - xpack.security.enabled=false
     - xpack.monitoring.collection.enabled=true
     - xpack.monitoring.exporters.remote.type=http
     - xpack.monitoring.exporters.remote.host=http://monitor:9200
     - discovery.zen.minimum_master_nodes=2
     - discovery.zen.ping.unicast.hosts=elasticsearch1,elasticsearch2,elasticsearch3
     - discovery.zen.fd.ping_timeout=5s
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 1g
    cap_add:
      - IPC_LOCK
    ports:
      - "29200:9200"
    networks:
      - esnet

  elasticsearch3:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.0
    container_name: elasticsearch3
    environment:
     - cluster.name=docker-cluster
     - bootstrap.memory_lock=true
     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
     - xpack.security.enabled=false
     - xpack.monitoring.collection.enabled=true
     - xpack.monitoring.exporters.remote.type=http
     - xpack.monitoring.exporters.remote.host=http://monitor:9200
     - discovery.zen.minimum_master_nodes=2
     - discovery.zen.ping.unicast.hosts=elasticsearch1,elasticsearch2,elasticsearch3
     - discovery.zen.fd.ping_timeout=5s
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 1g
    cap_add:
      - IPC_LOCK
    ports:
      - "39200:9200"
    networks:
      - esnet

  monitor:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.0
    container_name: monitor
    environment:
     - cluster.name=docker-monitor-cluster
     - bootstrap.memory_lock=true
     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
     - xpack.security.enabled=false
     - xpack.monitoring.enabled=false
     - xpack.monitoring.collection.enabled=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 1g
    cap_add:
      - IPC_LOCK
    ports:
      - "9200:9200"
    networks:
      - esnet

  kibana-devtools:
    image: docker.elastic.co/kibana/kibana:6.6.0
    container_name: kibana-devtools
    environment:
      ELASTICSEARCH_URL: http://elasticsearch3:9200
    ports:
      - "15601:5601"
    networks:
      - esnet

  kibana-dashboard:
    image: docker.elastic.co/kibana/kibana:6.6.0
    container_name: kibana-dashboard
    environment:
      ELASTICSEARCH_URL: http://monitor:9200
    ports:
      - "25601:5601"
    networks:
      - esnet

networks:
  esnet:
    driver: bridge
