version: "2"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.2
    container_name: elasticsearch-hands-on-2
    environment:
     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
     - "discovery.type=single-node"
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch-hands-on-2-data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:7.3.2
    environment:
      - "ELASTICSEARCH_URL=http://elasticsearch-hands-on-2:9200"
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

volumes:
  elasticsearch-hands-on-2-data:
    external: true

